Regex:Regular expression.

-regular expression we are using to match the pattern

-regular expression have there own characters

-we always write a regular expression in verbose form.

-regular espression alwys scan from left to right.

syntax:

    import re

functions in regular expression:

1.re.match()

2.re.findall()

3.re.sub()

4.re.search()

5.re.compile

characters in ReGEX:
1.  .(dot)--->it will match a single character

    .. --->2characters
	...--->3 characters
2. *---->match 0 or more chracters

3. +--->match 1 or more chracters

4. ?--->0 or 1 character

5. [a]--->matches a

   [ab]--->a or b

   [abc]--->a or b or c                          Meta Characters

   [a-z]--->

   [a-zA-Z0-9]
  
    a$-->ends with a

  
  
  masking:
  
  mayurkulkarni636@gmail.com
  
  m###############@gmail.com
  
  g1-->m
  g2-->ayurkulkarni636
  g3-->@
  g4--->gmail
  g5---->.
  g6--->com
  
  
  phone no:
       7777-6666-5555
	   
	   7##7-####-5##5

In [ ]:
import re

In [ ]:
string="fan"
pattern="..."
print(re.match(pattern,string))

<re.Match object; span=(0, 3), match='fan'>

In [ ]:
string[0:3]

'fan'

In [ ]:
string="ban"
pattern="f.n"
print(re.match(pattern,string))

None

In [ ]:
string="afnaaaaaa"
pattern=".?"
print(re.findall(pattern,string))

['a', 'f', 'n', 'a', 'a', 'a', 'a', 'a', 'a', '']

In [ ]:
string="aaaaaaaaa"
pattern="a+"
print(re.findall(pattern,string))

['aaaaaaaaa']

In [ ]:
string=""
pattern="a+"
print(re.findall(pattern,string))

[]

In [ ]:
string=""
pattern="a*"
print(re.findall(pattern,string))

['']

In [ ]:
string="mayur123"
pattern="[a-z0-9]+"
print(re.findall(pattern,string))

['mayur123']

In [ ]:
string="mayurkulkarni6667@gmail.com"
pattern=r"[a-z0-9]+\@[a-z]+\.[a-z]+"
print(re.findall(pattern,string))

['mayurkulkarni6667@gmail.com']

In [ ]:
str1="mayur@"
pattern=r"[a-z]+\@"
print(re.findall(pattern,str1))

['mayur@']

In [ ]:
str2="mayur133@#gmail.co.in"
pattern=r"[a-z0-9]+\@\#[a-z]+\.[a-z]+\.[a-z]+"
print(re.findall(pattern,str2))

['mayur133@#gmail.co.in']

In [ ]:
str3="I have a 4 apples and 3 oranges"
pattern=r"\d"
print(re.findall(pattern,str3))

['4', '3']

In [ ]:
str4="I born in 28 Nov 1996"
pattern=r'\d+'
print(re.findall(pattern,str4))

['28', '1996']

In [ ]:
#match that string which ends with apple
str5="i have apple and pineapple"
pattern="[a-z]"
print(re.findall(pattern,str5))

['i', 'h', 'a', 'v', 'e', 'a', 'p', 'p', 'l', 'e', 'a', 'n', 'd', 'p', 'i', 'n', 'e', 'a', 'p', 'p', 'l', 'e']

In [ ]:
str6="python is simple but Python is vast PYTHON"
pattern="[pP]ython"
print(re.findall(pattern,str6))

['python', 'Python']

In [ ]:
str7="<HTML>"
pattern="<[A-Z]+>"
print(re.findall(pattern,str7))

['<HTML>']

In [ ]:
str7="<HTML>"
pattern="<.*?>"
print(re.findall(pattern,str7))

['<HTML>']

In [ ]:
str7="https://regex101.com/"
pattern=r"https?\:\/\/[a-z0-9]+\.[a-z]+\/"
print(re.findall(pattern,str7))

['https://regex101.com/']

In [ ]:
str8="mayur/"
pattern=r"[a-z]+\/"
print(re.findall(pattern,str8))

['mayur/']

In [ ]:
str10="visit this url 'https://regex101.com/'"
pattern=r"https?\:\/\/[a-z0-9]+\.[a-z]+\/"
text=re.sub(pattern,"",str10)

In [ ]:
text

"visit this url ''"

In [ ]:
str11="mayur1234@$"
pattern=r"\w+"
print(re.findall(pattern,str11))

['mayur1234']

In [ ]:
str12="mayur1234@$"
pattern=r"\W+"
print(re.findall(pattern,str11))

['@$']

In [ ]:
str11="mayur1234@$"
pattern=r"\w+\W+"
print(re.findall(pattern,str11))

['mayur1234@$']

In [ ]:
str12="This is           python"
pattern=r"\s+"
print(re.findall(pattern,str12))

[' ', '           ']

In [ ]:
str12="This is           python"
pattern=r"\s+"
text1=re.sub(pattern," ",str12)

In [ ]:
text1

'This is python'

In [ ]:
str12="This is           python"
pattern=r"\S+"
print(re.findall(pattern,str12))

['This', 'is', 'python']

In [ ]:
string1="mayurkulkarni636@gmail.com"
pattern=r"([a-z])([a-z0-9]+)(\@)([a-z]+)(\.)([a-z]+)"
mtach=re.search(pattern,string1)

In [ ]:
mtach.group(1)

'm'

In [ ]:
mtach.group(2)

'ayurkulkarni636'

In [ ]:
mtach.group(3)

'@'

In [ ]:
mtach.group(4)

'gmail'

In [ ]:
mtach.group(5)

'.'

In [ ]:
mtach.group(6)

'com'

In [ ]:
ans=mtach.group(1) + len(mtach.group(2))*"#" +mtach.group(3) +mtach.group(4)+mtach.group(5)+mtach.group(6)

In [ ]:
ans

'm###############@gmail.com'

In [6]:
import pandas as pd
import numpy as np
import re

In [4]:
df=pd.read_csv("/content/nlp_preprocessing_dataset.csv")

In [5]:
df

    id                                               text
0    1  I LOVE NLP!!! 😍 Visit https://nlp.com for more...
1    2  <p>This is a HTML paragraph about NLP</p>   It...
2    3  Python is awsome for AI!!! Check https://pytho...
3    4  I realy like studying NLP 😊😊 It is sooo intere...
4    5  <div>Machine learning is powerfull</div> Learn...
5    6  Text preprocessing includes tokenization, stem...
6    7  This sentence has spelling erors and     too m...
7    8   Hello!!! How are you??? I'm learning NLP today 😃
8    9  Visit our WEBSITE at https://datascience.com f...
9   10  <h1>NLP Heading</h1> This text has HTML tags a...
10  11  I like Python programming...but sometimes it i...
11  12                    AI and NLP are the FUTURE!!! 🚀🚀
12  13  This line contains newline\nSee next line of t...
13  14            Too      many       spaces      here!!!
14  15  NLP preprocessing removes HTML, URLs, emojis 😊...
15  16  I LOOOVE data science!!! Visit https://datasci...
16  17  <b>Bold HTML text</b> with some random punctua...
17  18       Machine learning is amazng and very usefull.
18  19     Chatbots use NLP and AI to talk with humans!!!
19  20  Check this website https://ai-example.com for ...
20  21                  I realy enjoy coding in PYTHON!!!
21  22    <div>HTML content here</div> Learn NLP today!!!
22  23    Deep learning models work well with BIG DATA!!!
23  24        Spelling mistake exampple in this sentence.
24  25  Remove URLs like https://google.com and http:/...
25  26  I am HAPPY 😊 learning Natural Language Process...
26  27  Extra     spaces      everywhere      in     t...
27  28  HTML tags like <p>, <div>, <h1> should be remo...
28  29      Visit www.example.com for more INFORMATION!!!
29  30                AI is the FUTURE of TECHNOLOGY!!! 🚀
30  31         Python programming is funnn and powerfull.
31  32  This line has newline character\nSecond line h...
32  33  Check this link https://openai.com for AI rese...
33  34               I LOVE machine learning and NLP!!! 😍
34  35            Text preprocessing cleans messy data!!!
35  36                      Too much punctuation!!!???!!!
36  37    Some HTML <span>inline tags</span> appear here.
37  38         Speling mistakes are commmon in text data.
38  39             Remove emoji 😊😂👍 during preprocessing.
39  40  Sentence with UPPERCASE WORDS and lowercase wo...
40  41        Extra spaces should    be cleaned properly.
41  42         Visit https://nlp-course.com to learn NLP.
42  43        I realy realy like AI and machine learning.
43  44  <p>Paragraph HTML</p> with link https://exampl...
44  45       Numbers also appear 123 in some sentences!!!
45  46      Sentence with emoji 😃 and URL https://test.ai
46  47           Newline example\nAnother sentence below.
47  48         Data SCIENCE and AI are trending fields!!!
48  49      Preprocessing removes noise from TEXT DATA!!!
49  50   Final sentence with HTML <b>bold</b> and emoji 😊

In [7]:
def remove_new_line(text):
  pattern="\n"
  clean_text=re.sub(pattern,"",text)
  return clean_text

In [8]:
df["text"]=df["text"].apply(remove_new_line)

In [9]:
df

    id                                               text
0    1  I LOVE NLP!!! 😍 Visit https://nlp.com for more...
1    2  <p>This is a HTML paragraph about NLP</p>   It...
2    3  Python is awsome for AI!!! Check https://pytho...
3    4  I realy like studying NLP 😊😊 It is sooo intere...
4    5  <div>Machine learning is powerfull</div> Learn...
5    6  Text preprocessing includes tokenization, stem...
6    7  This sentence has spelling erors and     too m...
7    8   Hello!!! How are you??? I'm learning NLP today 😃
8    9  Visit our WEBSITE at https://datascience.com f...
9   10  <h1>NLP Heading</h1> This text has HTML tags a...
10  11  I like Python programming...but sometimes it i...
11  12                    AI and NLP are the FUTURE!!! 🚀🚀
12  13   This line contains newlineSee next line of text.
13  14            Too      many       spaces      here!!!
14  15  NLP preprocessing removes HTML, URLs, emojis 😊...
15  16  I LOOOVE data science!!! Visit https://datasci...
16  17  <b>Bold HTML text</b> with some random punctua...
17  18       Machine learning is amazng and very usefull.
18  19     Chatbots use NLP and AI to talk with humans!!!
19  20  Check this website https://ai-example.com for ...
20  21                  I realy enjoy coding in PYTHON!!!
21  22    <div>HTML content here</div> Learn NLP today!!!
22  23    Deep learning models work well with BIG DATA!!!
23  24        Spelling mistake exampple in this sentence.
24  25  Remove URLs like https://google.com and http:/...
25  26  I am HAPPY 😊 learning Natural Language Process...
26  27  Extra     spaces      everywhere      in     t...
27  28  HTML tags like <p>, <div>, <h1> should be remo...
28  29      Visit www.example.com for more INFORMATION!!!
29  30                AI is the FUTURE of TECHNOLOGY!!! 🚀
30  31         Python programming is funnn and powerfull.
31  32   This line has newline characterSecond line here.
32  33  Check this link https://openai.com for AI rese...
33  34               I LOVE machine learning and NLP!!! 😍
34  35            Text preprocessing cleans messy data!!!
35  36                      Too much punctuation!!!???!!!
36  37    Some HTML <span>inline tags</span> appear here.
37  38         Speling mistakes are commmon in text data.
38  39             Remove emoji 😊😂👍 during preprocessing.
39  40  Sentence with UPPERCASE WORDS and lowercase wo...
40  41        Extra spaces should    be cleaned properly.
41  42         Visit https://nlp-course.com to learn NLP.
42  43        I realy realy like AI and machine learning.
43  44  <p>Paragraph HTML</p> with link https://exampl...
44  45       Numbers also appear 123 in some sentences!!!
45  46      Sentence with emoji 😃 and URL https://test.ai
46  47             Newline exampleAnother sentence below.
47  48         Data SCIENCE and AI are trending fields!!!
48  49      Preprocessing removes noise from TEXT DATA!!!
49  50   Final sentence with HTML <b>bold</b> and emoji 😊

In [12]:
def remove_html_tags(text):
  pattern="<.*?>"
  clean_text=re.sub(pattern,"",text)
  return clean_text

In [13]:
df["text"]=df["text"].apply(remove_html_tags)

In [14]:
df

    id                                               text
0    1  I LOVE NLP!!! 😍 Visit https://nlp.com for more...
1    2  This is a HTML paragraph about NLP   It has ex...
2    3  Python is awsome for AI!!! Check https://pytho...
3    4  I realy like studying NLP 😊😊 It is sooo intere...
4    5  Machine learning is powerfull Learn at https:/...
5    6  Text preprocessing includes tokenization, stem...
6    7  This sentence has spelling erors and     too m...
7    8   Hello!!! How are you??? I'm learning NLP today 😃
8    9  Visit our WEBSITE at https://datascience.com f...
9   10  NLP Heading This text has HTML tags and URL ht...
10  11  I like Python programming...but sometimes it i...
11  12                    AI and NLP are the FUTURE!!! 🚀🚀
12  13   This line contains newlineSee next line of text.
13  14            Too      many       spaces      here!!!
14  15  NLP preprocessing removes HTML, URLs, emojis 😊...
15  16  I LOOOVE data science!!! Visit https://datasci...
16  17     Bold HTML text with some random punctuation!!!
17  18       Machine learning is amazng and very usefull.
18  19     Chatbots use NLP and AI to talk with humans!!!
19  20  Check this website https://ai-example.com for ...
20  21                  I realy enjoy coding in PYTHON!!!
21  22               HTML content here Learn NLP today!!!
22  23    Deep learning models work well with BIG DATA!!!
23  24        Spelling mistake exampple in this sentence.
24  25  Remove URLs like https://google.com and http:/...
25  26  I am HAPPY 😊 learning Natural Language Process...
26  27  Extra     spaces      everywhere      in     t...
27  28             HTML tags like , ,  should be removed.
28  29      Visit www.example.com for more INFORMATION!!!
29  30                AI is the FUTURE of TECHNOLOGY!!! 🚀
30  31         Python programming is funnn and powerfull.
31  32   This line has newline characterSecond line here.
32  33  Check this link https://openai.com for AI rese...
33  34               I LOVE machine learning and NLP!!! 😍
34  35            Text preprocessing cleans messy data!!!
35  36                      Too much punctuation!!!???!!!
36  37                 Some HTML inline tags appear here.
37  38         Speling mistakes are commmon in text data.
38  39             Remove emoji 😊😂👍 during preprocessing.
39  40  Sentence with UPPERCASE WORDS and lowercase wo...
40  41        Extra spaces should    be cleaned properly.
41  42         Visit https://nlp-course.com to learn NLP.
42  43        I realy realy like AI and machine learning.
43  44       Paragraph HTML with link https://example.org
44  45       Numbers also appear 123 in some sentences!!!
45  46      Sentence with emoji 😃 and URL https://test.ai
46  47             Newline exampleAnother sentence below.
47  48         Data SCIENCE and AI are trending fields!!!
48  49      Preprocessing removes noise from TEXT DATA!!!
49  50          Final sentence with HTML bold and emoji 😊

In [15]:
import string

In [19]:
exclude=list(string.punctuation)

In [20]:
exclude

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [23]:
def remove_punctuation(text):
  pattern="[" + re.escape("".join(exclude)) + "]"
  clean_text=re.sub(pattern,"",text)
  return clean_text

In [24]:
df["text"]=df["text"].apply(remove_punctuation)

In [25]:
df

    id                                               text
0    1       I LOVE NLP 😍 Visit httpsnlpcom for more info
1    2  This is a HTML paragraph about NLP   It has ex...
2    3       Python is awsome for AI Check httpspythonorg
3    4  I realy like studying NLP 😊😊 It is sooo intere...
4    5  Machine learning is powerfull Learn at httpsmlcom
5    6  Text preprocessing includes tokenization stemm...
6    7  This sentence has spelling erors and     too m...
7    8          Hello How are you Im learning NLP today 😃
8    9  Visit our WEBSITE at httpsdatasciencecom for D...
9   10  NLP Heading This text has HTML tags and URL ht...
10  11  I like Python programmingbut sometimes it is c...
11  12                       AI and NLP are the FUTURE 🚀🚀
12  13    This line contains newlineSee next line of text
13  14               Too      many       spaces      here
14  15  NLP preprocessing removes HTML URLs emojis 😊 a...
15  16     I LOOOVE data science Visit httpsdatascienceai
16  17        Bold HTML text with some random punctuation
17  18        Machine learning is amazng and very usefull
18  19        Chatbots use NLP and AI to talk with humans
19  20   Check this website httpsaiexamplecom for AI news
20  21                     I realy enjoy coding in PYTHON
21  22                  HTML content here Learn NLP today
22  23       Deep learning models work well with BIG DATA
23  24         Spelling mistake exampple in this sentence
24  25    Remove URLs like httpsgooglecom and httptestcom
25  26  I am HAPPY 😊 learning Natural Language Processing
26  27  Extra     spaces      everywhere      in     t...
27  28                HTML tags like    should be removed
28  29           Visit wwwexamplecom for more INFORMATION
29  30                   AI is the FUTURE of TECHNOLOGY 🚀
30  31          Python programming is funnn and powerfull
31  32    This line has newline characterSecond line here
32  33     Check this link httpsopenaicom for AI research
33  34                  I LOVE machine learning and NLP 😍
34  35               Text preprocessing cleans messy data
35  36                               Too much punctuation
36  37                  Some HTML inline tags appear here
37  38          Speling mistakes are commmon in text data
38  39              Remove emoji 😊😂👍 during preprocessing
39  40  Sentence with UPPERCASE WORDS and lowercase words
40  41         Extra spaces should    be cleaned properly
41  42               Visit httpsnlpcoursecom to learn NLP
42  43         I realy realy like AI and machine learning
43  44           Paragraph HTML with link httpsexampleorg
44  45          Numbers also appear 123 in some sentences
45  46          Sentence with emoji 😃 and URL httpstestai
46  47              Newline exampleAnother sentence below
47  48            Data SCIENCE and AI are trending fields
48  49         Preprocessing removes noise from TEXT DATA
49  50          Final sentence with HTML bold and emoji 😊

In [27]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 11.9 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [28]:
import emoji

In [31]:
def remove_emoji(text):
  clean_text = emoji.replace_emoji(text, replace='')
  return clean_text

In [32]:
df["text"] = df["text"].apply(remove_emoji)

In [33]:
df["text"] = df["text"].apply(remove_emoji)

In [34]:
df

    id                                               text
0    1        I LOVE NLP  Visit httpsnlpcom for more info
1    2  This is a HTML paragraph about NLP   It has ex...
2    3       Python is awsome for AI Check httpspythonorg
3    4  I realy like studying NLP  It is sooo interesting
4    5  Machine learning is powerfull Learn at httpsmlcom
5    6  Text preprocessing includes tokenization stemm...
6    7  This sentence has spelling erors and     too m...
7    8           Hello How are you Im learning NLP today
8    9  Visit our WEBSITE at httpsdatasciencecom for D...
9   10  NLP Heading This text has HTML tags and URL ht...
10  11  I like Python programmingbut sometimes it is c...
11  12                         AI and NLP are the FUTURE
12  13    This line contains newlineSee next line of text
13  14               Too      many       spaces      here
14  15  NLP preprocessing removes HTML URLs emojis  an...
15  16     I LOOOVE data science Visit httpsdatascienceai
16  17        Bold HTML text with some random punctuation
17  18        Machine learning is amazng and very usefull
18  19        Chatbots use NLP and AI to talk with humans
19  20   Check this website httpsaiexamplecom for AI news
20  21                     I realy enjoy coding in PYTHON
21  22                  HTML content here Learn NLP today
22  23       Deep learning models work well with BIG DATA
23  24         Spelling mistake exampple in this sentence
24  25    Remove URLs like httpsgooglecom and httptestcom
25  26   I am HAPPY  learning Natural Language Processing
26  27  Extra     spaces      everywhere      in     t...
27  28                HTML tags like    should be removed
28  29           Visit wwwexamplecom for more INFORMATION
29  30                    AI is the FUTURE of TECHNOLOGY
30  31          Python programming is funnn and powerfull
31  32    This line has newline characterSecond line here
32  33     Check this link httpsopenaicom for AI research
33  34                   I LOVE machine learning and NLP
34  35               Text preprocessing cleans messy data
35  36                               Too much punctuation
36  37                  Some HTML inline tags appear here
37  38          Speling mistakes are commmon in text data
38  39                 Remove emoji  during preprocessing
39  40  Sentence with UPPERCASE WORDS and lowercase words
40  41         Extra spaces should    be cleaned properly
41  42               Visit httpsnlpcoursecom to learn NLP
42  43         I realy realy like AI and machine learning
43  44           Paragraph HTML with link httpsexampleorg
44  45          Numbers also appear 123 in some sentences
45  46           Sentence with emoji  and URL httpstestai
46  47              Newline exampleAnother sentence below
47  48            Data SCIENCE and AI are trending fields
48  49         Preprocessing removes noise from TEXT DATA
49  50           Final sentence with HTML bold and emoji

In [42]:
def remove_extra_spaces(text):
  pattern="\s+"
  clean_text=re.sub(pattern," ",text)
  return clean_text

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_5507/3247506207.py:2: SyntaxWarning: invalid escape sequence '\s'
  pattern="\s+"

In [43]:
df["text"]=df["text"].apply(remove_extra_spaces)

In [44]:
df

    id                                               text
0    1                ILOVENLPVisithttpsnlpcomformoreinfo
1    2       ThisisaHTMLparagraphaboutNLPIthasextraspaces
2    3             PythonisawsomeforAICheckhttpspythonorg
3    4           IrealylikestudyingNLPItissooointeresting
4    5        MachinelearningispowerfullLearnathttpsmlcom
5    6  Textpreprocessingincludestokenizationstemmingl...
6    7       Thissentencehasspellingerorsandtoomanyspaces
7    8                   HelloHowareyouImlearningNLPtoday
8    9  VisitourWEBSITEathttpsdatasciencecomforDATASCI...
9   10  NLPHeadingThistexthasHTMLtagsandURLhttpexamplecom
10  11    IlikePythonprogrammingbutsometimesitisconfusing
11  12                               AIandNLParetheFUTURE
12  13           ThislinecontainsnewlineSeenextlineoftext
13  14                                  Toomanyspaceshere
14  15  NLPpreprocessingremovesHTMLURLsemojisandpunctu...
15  16          ILOOOVEdatascienceVisithttpsdatascienceai
16  17              BoldHTMLtextwithsomerandompunctuation
17  18              Machinelearningisamazngandveryusefull
18  19                ChatbotsuseNLPandAItotalkwithhumans
19  20         CheckthiswebsitehttpsaiexamplecomforAInews
20  21                          IrealyenjoycodinginPYTHON
21  22                       HTMLcontenthereLearnNLPtoday
22  23              DeeplearningmodelsworkwellwithBIGDATA
23  24              Spellingmistakeexamppleinthissentence
24  25         RemoveURLslikehttpsgooglecomandhttptestcom
25  26          IamHAPPYlearningNaturalLanguageProcessing
26  27                Extraspaceseverywhereinthissentence
27  28                        HTMLtagslikeshouldberemoved
28  29               VisitwwwexamplecomformoreINFORMATION
29  30                          AIistheFUTUREofTECHNOLOGY
30  31               Pythonprogrammingisfunnnandpowerfull
31  32          ThislinehasnewlinecharacterSecondlinehere
32  33           CheckthislinkhttpsopenaicomforAIresearch
33  34                         ILOVEmachinelearningandNLP
34  35                   Textpreprocessingcleansmessydata
35  36                                 Toomuchpunctuation
36  37                       SomeHTMLinlinetagsappearhere
37  38                Spelingmistakesarecommmonintextdata
38  39                     Removeemojiduringpreprocessing
39  40        SentencewithUPPERCASEWORDSandlowercasewords
40  41                 Extraspacesshouldbecleanedproperly
41  42                   VisithttpsnlpcoursecomtolearnNLP
42  43                IrealyrealylikeAIandmachinelearning
43  44               ParagraphHTMLwithlinkhttpsexampleorg
44  45                Numbersalsoappear123insomesentences
45  46                 SentencewithemojiandURLhttpstestai
46  47                 NewlineexampleAnothersentencebelow
47  48                  DataSCIENCEandAIaretrendingfields
48  49              PreprocessingremovesnoisefromTEXTDATA
49  50                  FinalsentencewithHTMLboldandemoji

In [45]:
df1=pd.read_csv("/content/urdu_noisy_sentiment_dataset.csv")

In [47]:
df1

                                     text sentiment
0          مجھے یہ پروڈکٹ بہت پسند آیا!!!  positive
1                       یہ بہت خراب ہے!!!  negative
2   <p>بہت اچھی سروس</p> دوبارہ خریدوں گا  positive
3               یہ سب سے برا تجربہ تھا!!!  negative
4          بہت زبردست!!! https://shop.com  positive
5                      پیسے ضائع ہوگئے!!!  negative
6                         میں بہت خوش ہوں  positive
7                    <div>برا تجربہ</div>  negative
8                  سب سے بہترین پروڈکٹ!!!  positive
9                       میں بہت مایوس ہوں  negative
10                        واہ!!! بہت اچھا  positive
11               ایک دن میں خراب ہوگیا!!!  negative
12                   <b>مجھے پسند آیا</b>  positive
13                     بہت ہی خراب پروڈکٹ  negative
14                        فاسٹ ڈیلیوری!!!  positive
15                    ڈیلیوری بہت لیٹ تھی  negative
16                          مجھے اچھا لگا  positive
17           ٹھیک ہے لیکن زیادہ اچھا نہیں  negative
18              <html>بہت اچھا ڈیل</html>  positive
19                  براہ کرم ریفنڈ دیں!!!  negative
20                         عمدہ کوالٹی!!!  positive
21                       خراب کسٹمر سپورٹ  negative
22                            بہت اچھا!!!  positive
23                     قیمت کے مطابق نہیں  negative
24             میں ضرور recommend کروں گا  positive
25                     کام کرنا بند ہوگیا  negative
26               <span>اچھا پروڈکٹ</span>  positive
27                             بہت برا!!!  negative
28    دوبارہ آرڈر کروں گا https://buy.com  positive
29                           ٹوٹا ہوا ملا  negative
30                       بہت ہی زبردست!!!  positive
31                            سستی کوالٹی  negative
32                     مجھے بہت خوشی ہوئی  positive
33                            بہت خراب!!!  negative
34                        <h1>پرفیکٹ</h1>  positive
35                 باکس میں آئٹم نہیں تھا  negative
36                   بہت اچھا کام کرتا ہے  positive
37                    بہت برا سمیل آتا ہے  negative
38                          میں مطمئن ہوں  positive
39                      پیسے ضائع مت کریں  negative
40                              لاجواب!!!  positive
41                         بہت سلو رسپانس  negative
42                قیمت کے لحاظ سے اچھا ہے  positive
43                        پیکجنگ خراب تھی  negative
44             مجھے استعمال کرنا پسند آیا  positive
45                       بہت برا تجربہ!!!  negative
46                         اچھی سپورٹ ٹیم  positive
47                        اسٹاف بدتمیز ہے  negative
48                         بہت خوبصورت!!!  positive
49             میں recommend نہیں کروں گا  negative

In [48]:
df1["text"]=df1["text"].apply(remove_punctuation)

In [49]:
df1

                                text sentiment
0        مجھے یہ پروڈکٹ بہت پسند آیا  positive
1                     یہ بہت خراب ہے  negative
2   pبہت اچھی سروسp دوبارہ خریدوں گا  positive
3             یہ سب سے برا تجربہ تھا  negative
4            بہت زبردست httpsshopcom  positive
5                    پیسے ضائع ہوگئے  negative
6                    میں بہت خوش ہوں  positive
7                    divبرا تجربہdiv  negative
8                سب سے بہترین پروڈکٹ  positive
9                  میں بہت مایوس ہوں  negative
10                      واہ بہت اچھا  positive
11             ایک دن میں خراب ہوگیا  negative
12                   bمجھے پسند آیاb  positive
13                بہت ہی خراب پروڈکٹ  negative
14                      فاسٹ ڈیلیوری  positive
15               ڈیلیوری بہت لیٹ تھی  negative
16                     مجھے اچھا لگا  positive
17      ٹھیک ہے لیکن زیادہ اچھا نہیں  negative
18              htmlبہت اچھا ڈیلhtml  positive
19                براہ کرم ریفنڈ دیں  negative
20                       عمدہ کوالٹی  positive
21                  خراب کسٹمر سپورٹ  negative
22                          بہت اچھا  positive
23                قیمت کے مطابق نہیں  negative
24        میں ضرور recommend کروں گا  positive
25                کام کرنا بند ہوگیا  negative
26               spanاچھا پروڈکٹspan  positive
27                           بہت برا  negative
28   دوبارہ آرڈر کروں گا httpsbuycom  positive
29                      ٹوٹا ہوا ملا  negative
30                     بہت ہی زبردست  positive
31                       سستی کوالٹی  negative
32                مجھے بہت خوشی ہوئی  positive
33                          بہت خراب  negative
34                        h1پرفیکٹh1  positive
35            باکس میں آئٹم نہیں تھا  negative
36              بہت اچھا کام کرتا ہے  positive
37               بہت برا سمیل آتا ہے  negative
38                     میں مطمئن ہوں  positive
39                 پیسے ضائع مت کریں  negative
40                            لاجواب  positive
41                    بہت سلو رسپانس  negative
42           قیمت کے لحاظ سے اچھا ہے  positive
43                   پیکجنگ خراب تھی  negative
44        مجھے استعمال کرنا پسند آیا  positive
45                     بہت برا تجربہ  negative
46                    اچھی سپورٹ ٹیم  positive
47                   اسٹاف بدتمیز ہے  negative
48                       بہت خوبصورت  positive
49        میں recommend نہیں کروں گا  negative

In [51]:
def remove_word(text):
  pattern="[a-z]"
  clean_text=re.sub(pattern," ",text)
  return clean_text

In [52]:
df1["text"]=df1["text"].apply(remove_word)

In [53]:
df1

                                text sentiment
0        مجھے یہ پروڈکٹ بہت پسند آیا  positive
1                     یہ بہت خراب ہے  negative
2    بہت اچھی سروس  دوبارہ خریدوں گا  positive
3             یہ سب سے برا تجربہ تھا  negative
4            بہت زبردست               positive
5                    پیسے ضائع ہوگئے  negative
6                    میں بہت خوش ہوں  positive
7                       برا تجربہ     negative
8                سب سے بہترین پروڈکٹ  positive
9                  میں بہت مایوس ہوں  negative
10                      واہ بہت اچھا  positive
11             ایک دن میں خراب ہوگیا  negative
12                    مجھے پسند آیا   positive
13                بہت ہی خراب پروڈکٹ  negative
14                      فاسٹ ڈیلیوری  positive
15               ڈیلیوری بہت لیٹ تھی  negative
16                     مجھے اچھا لگا  positive
17      ٹھیک ہے لیکن زیادہ اچھا نہیں  negative
18                  بہت اچھا ڈیل      positive
19                براہ کرم ریفنڈ دیں  negative
20                       عمدہ کوالٹی  positive
21                  خراب کسٹمر سپورٹ  negative
22                          بہت اچھا  positive
23                قیمت کے مطابق نہیں  negative
24        میں ضرور           کروں گا  positive
25                کام کرنا بند ہوگیا  negative
26                   اچھا پروڈکٹ      positive
27                           بہت برا  negative
28   دوبارہ آرڈر کروں گا              positive
29                      ٹوٹا ہوا ملا  negative
30                     بہت ہی زبردست  positive
31                       سستی کوالٹی  negative
32                مجھے بہت خوشی ہوئی  positive
33                          بہت خراب  negative
34                         1پرفیکٹ 1  positive
35            باکس میں آئٹم نہیں تھا  negative
36              بہت اچھا کام کرتا ہے  positive
37               بہت برا سمیل آتا ہے  negative
38                     میں مطمئن ہوں  positive
39                 پیسے ضائع مت کریں  negative
40                            لاجواب  positive
41                    بہت سلو رسپانس  negative
42           قیمت کے لحاظ سے اچھا ہے  positive
43                   پیکجنگ خراب تھی  negative
44        مجھے استعمال کرنا پسند آیا  positive
45                     بہت برا تجربہ  negative
46                    اچھی سپورٹ ٹیم  positive
47                   اسٹاف بدتمیز ہے  negative
48                       بہت خوبصورت  positive
49        میں           نہیں کروں گا  negative

In [54]:
def remove_numbers(text):
  pattern="[0-9]"
  clean_text=re.sub(pattern," ",text)
  return clean_text

In [55]:
df1["text"]=df1["text"].apply(remove_numbers)

In [56]:
df1

                                text sentiment
0        مجھے یہ پروڈکٹ بہت پسند آیا  positive
1                     یہ بہت خراب ہے  negative
2    بہت اچھی سروس  دوبارہ خریدوں گا  positive
3             یہ سب سے برا تجربہ تھا  negative
4            بہت زبردست               positive
5                    پیسے ضائع ہوگئے  negative
6                    میں بہت خوش ہوں  positive
7                       برا تجربہ     negative
8                سب سے بہترین پروڈکٹ  positive
9                  میں بہت مایوس ہوں  negative
10                      واہ بہت اچھا  positive
11             ایک دن میں خراب ہوگیا  negative
12                    مجھے پسند آیا   positive
13                بہت ہی خراب پروڈکٹ  negative
14                      فاسٹ ڈیلیوری  positive
15               ڈیلیوری بہت لیٹ تھی  negative
16                     مجھے اچھا لگا  positive
17      ٹھیک ہے لیکن زیادہ اچھا نہیں  negative
18                  بہت اچھا ڈیل      positive
19                براہ کرم ریفنڈ دیں  negative
20                       عمدہ کوالٹی  positive
21                  خراب کسٹمر سپورٹ  negative
22                          بہت اچھا  positive
23                قیمت کے مطابق نہیں  negative
24        میں ضرور           کروں گا  positive
25                کام کرنا بند ہوگیا  negative
26                   اچھا پروڈکٹ      positive
27                           بہت برا  negative
28   دوبارہ آرڈر کروں گا              positive
29                      ٹوٹا ہوا ملا  negative
30                     بہت ہی زبردست  positive
31                       سستی کوالٹی  negative
32                مجھے بہت خوشی ہوئی  positive
33                          بہت خراب  negative
34                          پرفیکٹ    positive
35            باکس میں آئٹم نہیں تھا  negative
36              بہت اچھا کام کرتا ہے  positive
37               بہت برا سمیل آتا ہے  negative
38                     میں مطمئن ہوں  positive
39                 پیسے ضائع مت کریں  negative
40                            لاجواب  positive
41                    بہت سلو رسپانس  negative
42           قیمت کے لحاظ سے اچھا ہے  positive
43                   پیکجنگ خراب تھی  negative
44        مجھے استعمال کرنا پسند آیا  positive
45                     بہت برا تجربہ  negative
46                    اچھی سپورٹ ٹیم  positive
47                   اسٹاف بدتمیز ہے  negative
48                       بہت خوبصورت  positive
49        میں           نہیں کروں گا  negative